spring:
  datasource:
    url: jdbc:h2:file:~/spring_tests/sudoku_db/db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
